### ISSUE TITLE
Gas allocation at 0

### ISSUE THREAD

**Issue by freshbtcer** [oraclesorg/ico-wizard#206] opened 2017-10-03 01:17 UTC
Processing 3 tier ICO, at least 6 contracts needed to be signed where gas limit was not filled in, was unsure of amount and might be a reason why contracts failed not knowing the amount of gas to send to each one.

**Comment by vbaranov** [comment] 2017-10-03 14:55
We can't reproduce the issue with 3-tier contract. 
Could you reproduce it to share the video with us? Or to point us, what parameters of crowdsale you've set?

**Comment by freshbtcer** [comment] 2017-10-04 05:26
https://pastebin.com/d0J7dsBe

while running icowizard locally there are some errors, check out the paste bin for some of the information.. I can get the whole thing if needed, but this one was run in a multiplexer so I couldn't scroll.

**Comment by igorbarinov** [comment] 2017-10-04 06:19
>  I did notice however, these contracts are still using "throw" which means they aren't updated.

it's ok. we use proven TokenMarket contracts as a base. We will incrementally update them and include Safemath from OpenZeppelin in the future.

**Comment by freshbtcer** [comment] 2017-10-04 08:34
is there a chat channel you reside in? gitter, irc, slack? I am attemmpting another single tier and it came up with a transaction with 36 bytes of data gas limit set at 0 and gas price at 21... i have a screen shot of it but its on my other computer.. lmk

**Comment by igorbarinov** [comment] 2017-10-04 08:35
@freshbtcer we have a telegram chat here https://t.me/oraclesnetwork

**Comment by freshbtcer** [comment] 2017-10-04 08:39
lol figures i cant get into that right now as my phone broke and ive been locked in this room for a week losing my mind and cant sign up for telegram without sms and i dont feel like searching for a pc version.. im guessing a transaction sending only 36 bytes should only be a little over $1 usd in gas?

**Comment by vbaranov** [comment] 2017-10-04 13:27
>while running icowizard locally there are some errors, check out the paste bin for some of the >information.. I can get the whole thing if needed, but this one was run in a multiplexer so I couldn't >scroll.

These warnings don't affect ICO wizard logic. We should ignore them.

@freshbtcer if you have any screenshot or video describing your problem, it'll be very helpful to solve it.

**Comment by vbaranov** [comment] 2017-10-06 14:48
@freshbtcer could you check https://wizard-stage.oracles.org/ ? Are you faced with this bug there?
If it is fixed there, we'll merge it to the main branch.

**Comment by vbaranov** [comment] 2017-10-07 02:45
Anyway, we merged this fix to [https://wizard.oracles.org/](https://wizard.oracles.org/). We'll appreciate your feedback.

**Comment by freshbtcer** [comment] 2017-10-07 03:09
Hey, sorry didn't get back to you sooner. I tried it out on the testnet and all the gas worked out and it deployed, I just didn't get to test it out because got called away to help with the kids and forgot about it. It happened on the main net though, I will try again soon let you know.

**Comment by vbaranov** [comment] 2017-10-10 14:12
We have repaired the life cycle of ICO Wizard in mainnet. Thank you for the report!

**Closed** 2017-10-11 21:35 UTC
Labels: bug, Step3-CrowdsaleSetup
